export const alphabet = [
  { letter: "A", bgColor: "bg-amber-400" },
  { letter: "B", bgColor: "bg-amber-400" },
  { letter: "C", bgColor: "bg-amber-400" },
  { letter: "D", bgColor: "bg-amber-400" },
  { letter: "E", bgColor: "bg-amber-400" },
  { letter: "F", bgColor: "bg-amber-400" },
  { letter: "G", bgColor: "bg-amber-400" },
  { letter: "H", bgColor: "bg-amber-400" },
  { letter: "I", bgColor: "bg-amber-400" },
  { letter: "J", bgColor: "bg-amber-400" },
  { letter: "K", bgColor: "bg-amber-400" },
  { letter: "L", bgColor: "bg-amber-400" },
  { letter: "M", bgColor: "bg-amber-400" },
  { letter: "N", bgColor: "bg-amber-400" },
  { letter: "O", bgColor: "bg-amber-400" },
  { letter: "P", bgColor: "bg-amber-400" },
  { letter: "Q", bgColor: "bg-amber-400" },
  { letter: "R", bgColor: "bg-amber-400" },
  { letter: "S", bgColor: "bg-amber-400" },
  { letter: "T", bgColor: "bg-amber-400" },
  { letter: "U", bgColor: "bg-amber-400" },
  { letter: "V", bgColor: "bg-amber-400" },
  { letter: "W", bgColor: "bg-amber-400" },
  { letter: "X", bgColor: "bg-amber-400" },
  { letter: "Y", bgColor: "bg-amber-400" },
  { letter: "Z", bgColor: "bg-amber-400" },
];
